#Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
*a) Addition of 2 in all the element*
*b) Multiply 3 with all the elements*
*c) Divide every element by 2*

In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a+2)
print(a*3)
print(a/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


##Q.2 Questions on Basic NumPy Array:
*a. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])*

In [5]:
import numpy as np
b=np.array([1, 2, 3, 6, 4, 5])
print(b)
rev=np.flip(b)
print(rev)

[1 2 3 6 4 5]
[5 4 6 3 2 1]


*b.Find the most frequent value and their indice(s) in the following arrays:*
* i. x = np.array([1,2,3,4,5,1,2,1,1,1])
* ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [16]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3,])
print("Most frequent value in above array")
g = np.bincount(x)
maximum = max(g)

for i in range(len(g)):
    if g[i] == maximum:
        print(i, end=" " "\n")

print("Most frequent value in above array ")

f = np.bincount(y)
maximum = max(f)

for i in range(len(f)):
    if f[i] == maximum:
        print(i, end=" ")


Most frequent value in above array
1 
Most frequent value in above array 
3 

# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
* a) Access 1st row, 2nd column
* b) Access 3rd row, 1st column

In [19]:
import numpy as np
arr= np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


#Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [24]:
import numpy as np

spaced_arr = np.linspace(10, 100, 25)

print("Array:", spaced_arr)
print("Dimensions of the array:", spaced_arr.ndim)
print("Shape of the array:", spaced_arr.shape)
print("Total number of elements:", spaced_arr.size)
print("Data type of each element:", spaced_arr.dtype)
print("Total number of bytes consumed by the array:", spaced_arr.nbytes)

spaced_arr_transposed = spaced_arr.reshape(25, 1)
print("Transposed Array using reshape():\n", spaced_arr_transposed)
spaced_arr_T = spaced_arr.T
print("Transposed Array using T attribute:\n", spaced_arr_T)
## No, the .T attribute does not affect a 1-D array since it remains a 1-D row vector. Only reshaping changes its structure. ##

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total number of elements: 25
Data type of each element: float64
Total number of bytes consumed by the array: 200
Transposed Array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed Array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


# Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [33]:
import numpy as np
ucs420= np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]])
mean_value = np.mean(ucs420)
median_value = np.median(ucs420)
max_value = np.max(ucs420)
min_value = np.min(ucs420)
unique_elements = np.unique(ucs420)
print("Original 2-D Array:\n", ucs420,"\n")
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique elements:", unique_elements,"\n")
reshaped_ucs420 = ucs420.reshape(4,3)
resized_ucs420 = np.resize(ucs420, (2,3))
print(reshaped_ucs420 ,"\n")
print(resized_ucs420 ,"\n")

Original 2-D Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]] 

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90] 

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]] 

[[10 20 30]
 [40 50 60]] 

